name       : python-svglib
version    : 1.4.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/ee/cd/8b19f6299541862deea19b26a9efe269ff843fa15a9fd833ff0fec2ac22c/svglib-1.4.1.tar.gz : 48c24706c23bb4262173b6fa49eabb10afa15b8412f14283120549517ccfa314
license    : LGPL-3.0-only
homepage   : https://github.com/deeplook/svglib
component  : programming.python
summary    : A pure-Python library for reading and converting SVG
description: |
    svglib is a pure-Python library for reading SVG files and converting them (to a reasonable degree) to other formats using the ReportLab Open Source toolkit
rundeps    :
    - python-cssselect2
    - python-lxml
    - python-reportlab
build      : |
    %python3_setup
install    : |
    %python3_install
